trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'gis/adminapp:$(build.buildNumber)'

steps:
- task: Docker@1
  displayName: Build an image
  inputs:
    command: Build an image
    containerregistrytype: Azure Container Registry
    dockerRegistryEndpoint: GISDockerRegistry
    dockerFile: $(build.sourcesdirectory)/Applications/AdminManagementApp/Dockerfile
    imageName: $(imageName)
    imageNamesPath: 
    restartPolicy: always
- task: Docker@1
  displayName: Push an image
  inputs:
    command: Push an image
    containerregistrytype: Azure Container Registry
    dockerRegistryEndpoint: GISDockerRegistry
    dockerFile: $(build.sourcesdirectory)/Applications/AdminManagementApp/Dockerfile
    imageName: $(imageName)
    imageNamesPath: 
    restartPolicy: always
