pool:
  name: Azure Pipelines
#Your build pipeline references an undefined variable named ‘BuildConfiguration’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet '
  inputs:
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: EventFramework/Messaging.sln
    vstsFeed: '8641428b-255c-4810-87f1-24d0742ee9ba'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(build.sourcesdirectory)/EventFramework/Messaging/Messaging.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '$(build.sourcesdirectory)/EventFramework/Messaging.Tests/Messaging.Tests.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: EventFramework/Messaging/Messaging.csproj

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: '8641428b-255c-4810-87f1-24d0742ee9ba'
