pool:
  name: Azure Pipelines
#Your build pipeline references an undefined variable named ‘BuildConfiguration’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet '
  inputs:
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: RenderingFramework/TileFactory.sln
    vstsFeed: 'e61822ea-e45c-482a-b8b9-1fadca5217cc/d0ddad52-9144-4ca3-985d-75d86712761d'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(build.sourcesdirectory)/RenderingFramework/TileFactory/TileFactory.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '$(build.sourcesdirectory)/RenderingFramework/TileFactory.Tests/TileFactory.Tests.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: /RenderingFramework/TileFactory/TileFactory.csproj
    includeSymbols: true

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'e61822ea-e45c-482a-b8b9-1fadca5217cc/d0ddad52-9144-4ca3-985d-75d86712761d'
